debug: true
logging:
  level:
    root: debug
server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      stat-view-servlet:
        allow: true
      test-on-borrow: true
    password: opopop
    url: jdbc:mysql://192.168.1.12:3306/springboot_demo
    username: root
  thymeleaf:
    cache: false